# Generated by Django 4.2.6 on 2023-11-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designpro', '0002_adminprofile_designrequest_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено')], default='Новая', max_length=20, verbose_name='Статус'),
        ),
    ]
