# Generated by Django 4.2.6 on 2023-11-06 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designpro', '0003_alter_designrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='design_image',
            field=models.ImageField(blank=True, upload_to='design_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])], verbose_name='Изображение дизайна'),
        ),
    ]
