# Generated by Django 4.2.6 on 2023-11-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designpro', '0004_designrequest_comment_designrequest_design_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='design_image',
        ),
        migrations.AddField(
            model_name='designrequest',
            name='design',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено')], default='Новая', max_length=50),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
