# Generated by Django 4.2.6 on 2023-11-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designpro', '0005_remove_designrequest_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='designrequest',
            name='design',
        ),
        migrations.AlterField(
            model_name='designrequest',
            name='status',
            field=models.CharField(default='Новая', max_length=20, verbose_name='Статус'),
        ),
    ]
