# Generated by Django 4.2.6 on 2023-11-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designpro', '0008_remove_designrequest_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='current_status',
            field=models.CharField(default='Новая', max_length=20, verbose_name='Текущий статус'),
        ),
    ]
